### ISSUE TITLE
Allow using `nib` from the command line

### ISSUE THREAD

**Issue by rstacruz** [DamonOehlman/stylify#12] opened 2015-03-03 08:38 UTC
It would be nice to be able to do:

```
browserify -t [ stylify --use nib ]
```

...and have nib be automatically picked up. This currently won't work (the `use` option expects an actual plugin, not a string).

**Comment by rstacruz** [comment] 2015-03-03 08:44
Also, #5 - it would be nice to document CLI usage!

**Comment by contra** [comment] 2015-03-03 09:46
duplicate of https://github.com/DamonOehlman/stylify/issues/9

**Closed by contra** 2015-03-03 09:46 UTC

**Comment by rstacruz** [comment] 2015-03-03 10:34
Thanks, I'm a little unfamiliar with the code of stylify at the moment, but does this mean I can actually do `--use modulename`?

How does that factor into nib, which needs `use: require("nib")()` instead of `use: require("nib")` ?

**Comment by rstacruz** [comment] 2015-03-03 12:34
Okay, just used your branch and indeed, it's as easy as `-t [ stylify --use nib ]` ;)
