### ISSUE TITLE
1.3 gives errors with plugins

### ISSUE THREAD

**Issue by appedemic** [DamonOehlman/stylify#15] opened 2015-08-12 11:53 UTC
With 1.3.0 I'm getting an error when bundling with browserify:

```
/appedemic/weberapps/osseus/node_modules/nib/lib/nib.js:51
    style.include(__dirname);
         ^
TypeError: Cannot read property 'include' of undefined
    at /appedemic/weberapps/osseus/node_modules/nib/lib/nib.js:51:10
    at /appedemic/weberapps/osseus/node_modules/stylify/index.js:70:13
    at Array.map (native)
    at resolveUses (/appedemic/weberapps/osseus/node_modules/stylify/index.js:63:15)
    at module.exports (/appedemic/weberapps/osseus/node_modules/stylify/index.js:126:17)
    at makeTransform (/appedemic/weberapps/osseus/node_modules/browserify/node_modules/module-deps/index.js:253:21)
    at /appedemic/weberapps/osseus/node_modules/browserify/node_modules/module-deps/index.js:228:9
    at Deps.getTransforms (/appedemic/weberapps/osseus/node_modules/browserify/node_modules/module-deps/index.js:233:7)
    at /appedemic/weberapps/osseus/node_modules/browserify/node_modules/module-deps/index.js:368:24
    at onresolve (/appedemic/weberapps/osseus/node_modules/browserify/node_modules/module-deps/index.js:178:14)
```

My transform is defined as:
```
  .transform(stylify, {
    use: [
      nib(),
      autoprefixer({ browsers: ['iOS >= 7', 'Android >= 4.4'], cascade: false })
    ],
    set: { compress: true },
    include: ['./node_modules/']
  })
```

With 1.2 this worked fine.

**Comment by DamonOehlman** [comment] 2015-08-12 12:15
@appedemic thanks for reporting, will take a look to see if I can work out what is going on.

**Comment by DamonOehlman** [comment] 2015-08-12 12:48
OK, it looks like the problem is where the `resolveUses` [automatically calls a function if it's been passed as a use option](https://github.com/DamonOehlman/stylify/blob/master/index.js#L69-L71).  Current master has a repro test case of what is being observed, and can be resolved by commenting out the lines in the referenced commit.  I'm hesitant to do this though until @contra gets a chance to look at this issue and perhaps give a heads up on the intention of that code.

If it's not used by anyone, then I reckon we remove it and assume that the person specifying `use` options is setting things up correctly (especially given that autoprefixer needs to be initialized before being passed in).

@appedemic Are you right to keep using `1.2.0` while we get this resolved?

**Comment by contra** [comment] 2015-08-12 17:54
@DamonOehlman It was to support `include: [require('some-thing')]`

**Comment by DamonOehlman** [comment] 2015-08-12 23:05
@contra Cool thanks - I'll remove it for now and publish `1.3.1`

**Comment by DamonOehlman** [comment] 2015-08-12 23:09
Published `1.3.1`

**Closed by DamonOehlman** 2015-08-12 23:09 UTC

**Comment by appedemic** [comment] 2015-08-13 08:14
Thanks! Works great now

**Comment by contra** [comment] 2015-09-12 17:56
Oh - wait a second. I know why that was in there. nib. Which doesn't work now that this branch was removed.

**Comment by contra** [comment] 2015-09-12 17:58
Example:

```js
  "stylify": {
    "use": [
      "nib",
      "jeet"
    ]
  },
```
